### ISSUE TITLE
Connection Error!!!

### ISSUE THREAD

**Issue by AlirezaTabaei** [mohsenalipour/algotik_tse#1]
زمانیکه میخواد اطلاعات یک سهام مثل شتران رو بخونه conection error میده که فک کنم نمیتونه به tse اصلاً وصل بشه. مشکلش رو چجوری حل کنم؟

**Comment by mohsenalipour** [comment]
سلام وقت بخیر
کانکشن ارور موقعی اتفاق میفته که وی پی ان شما روشن باشه. چون داده ها از سایت فناوری بورس دریافت میشه، از آی پی خارج از ایران نمیشه بهش دسترسی داشت.
من همین الان تست گرفتم، ماژول به خوبی کار می کرد. تصویر پیوست خروجی قیمت
های سهم شتران هستش.

**Comment by mohsenalipour** [comment]
![output of algotik-tse](https://github.com/mohsenalipour/algotik_tse/assets/56033255/66cc224c-91d2-41bb-9607-9a68149610f1)
